
CREATE TABLE TABELA (
    ID           VARCHAR(36) NOT NULL,
    NOME         VARCHAR(255),
    ATUALIZACAO  TIMESTAMP,
    CRIACAO      TIMESTAMP,
    PAGINA       INTEGER,
    VALOR        DECIMAL(15,2),
    CARTA        BLOB,
    FOTO         BLOB,
    STATUS       CHAR(1)
);

ALTER TABLE TABELA ADD CONSTRAINT PK_TABELA PRIMARY KEY (ID);

